services:
  genbuilder:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    ports:
      - "8200:8000"
    env_file:
      - .env.development
    restart: always
