services:
  genbuilder:
    build:
      context: .
      dockerfile: Dockerfile
    image: sandrro/genbuilder_api:latest
    ports:
      - "8200:8000"
    env_file:
      - .env.development
    volumes:
      - runtime_config:/runtime-config

volumes:
  runtime_config:
