name: build
on: workflow_dispatch
env:
  IMAGE_NAME: ${{secrets.REGISTRY}}/genbuilder
  CONTAINER_NAME: genbuilder_api
  
jobs:
  build:
    runs-on: self-hosted
    outputs:
      now: ${{steps.build.outputs.now}}
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
      - name: checkout
        uses: actions/checkout@v4
      - name: copy_keys
        env:
          KEYS_PATH: ${{secrets.KEYS_PATH}}
        run: cp -R "$KEYS_PATH" ./app/
      - name: copy_env
        env:
          ENV_PATH: ${{secrets.ENV_PATH}}
        run: cp "$ENV_PATH"/.env.development ./
      - name: build
        run: docker build -t "$IMAGE_NAME":"$NOW" .
      - name: push_to_registry
        run: docker push "$IMAGE_NAME":"$NOW"
  stop_container:
    runs-on: self-hosted
    needs: build
    steps:
      - name: stop_container
        run: docker rm -f "$CONTAINER_NAME"
  run_container:
    runs-on: self-hosted
    needs: [build, stop_container]
    env:
      NOW: ${{needs.build.outputs.now}}
    steps:
      - name: run
        run: docker run -d --name "$CONTAINER_NAME" --env-file ./.env.development -p 8210:8000 "$IMAGE_NAME":"$NOW"
